#### Import Statements

In [5]:
import pandas as pd

#### Constants

In [30]:
smite_additive_factor = 2.5
crit_multiplier = 1.5
zombified_piglin_damage_needed = 20.5

In [2]:
def calculate_damage_amounts(base_damage):
    reg_hits = {i:base_damage + smite_additive_factor*i for i in range(6)}
    crits = {i:base_damage*crit_multiplier + smite_additive_factor*i for i in range(6)}
    return reg_hits, crits

In [12]:
weapon_to_base_damage = {"Wooden Sword":4 ,     "Wooden Axe":7, 
                         "Gold Sword":4,        "Gold Axe":7, 
                         "Stone Sword":5,       "Stone Axe":9, 
                         "Iron Sword":6,        "Iron Axe":9, 
                         "Diamond Sword":7,     "Diamond Axe":9,
                         "Netherite Sword":8,   "Netherite Axe":10}
# keep the names in order using a list
weapon_names = ["Wooden Sword", "Wooden Axe", "Gold Sword", "Gold Axe", "Stone Sword", "Stone Axe", 
                "Iron Sword", "Iron Axe", "Diamond Sword", "Diamond Axe", "Netherite Sword", "Netherite Axe"]
index_list = ["Base", "Smite I", "Smite II", "Smite III", "Smite IV", "Smite V", 
              "Crit", "Smite I Crit", "Smite II Crit", "Smite III Crit", "Smite IV Crit", "Smite V Crit"]

In [42]:
weapon_to_damage_list = {}
for name in weapon_names:
    reg_hits, crits = calculate_damage_amounts(weapon_to_base_damage[name])
    damage_list = [reg_hits[i] for i in range(6)] + [crits[i] for i in range(6)]
    weapon_to_damage_list[name] = damage_list

df = pd.DataFrame(weapon_to_damage_list, index=index_list)
df.round(1)
#display(df)

def style_negative(v, props=''):
    return props if v > 20 else None

df = df.style.applymap(style_negative, props='background:red;color:white;font-weight: bold').format('{:.1f}')

df